name       : zeal
version    : 0.2.1
release    : 3
source     :
    - https://github.com/zealdocs/zeal/archive/v0.2.1.tar.gz : 994c5fad079cb34952fc05b0663920118489ed7f00f8e5a5887ff2e2bd05861d
license    : GPL-3.0
component  : programming.tools
summary    : Offline documentation browser inspired by Dash
description: |
    Offline documentation browser inspired by Dash
builddeps  :
    - pkgconfig(glesv2)
    - pkgconfig(libarchive)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(x11-xcb)
    - pkgconfig(xcb-keysyms)
setup      : |
    qmake CONFIG+=no_libappindicator
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
