name       : zeal
version    : 0.3.1
release    : 5
source     :
    - https://github.com/zealdocs/zeal/archive/v0.3.1.tar.gz : 55f8511977818612e00ae87a4fddaa346210189531469690f2e3961bb4c2c318
license    : GPL-3.0
component  : programming.tools
summary    : Offline documentation browser inspired by Dash
description: |
    Offline documentation browser inspired by Dash
builddeps  :
    - pkgconfig(glesv2)
    - pkgconfig(libarchive)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11-xcb)
    - pkgconfig(xcb-keysyms)
setup      : |
    %qmake CONFIG+=no_libappindicator
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
