name       : zeal
version    : 0.4.0
release    : 6
source     :
    - https://github.com/zealdocs/zeal/archive/v0.4.0.tar.gz : 1f6b50026036923ae0cfbf3f4eb1066ee2fdaf0425d4c321203e0dd9506823fd
license    : GPL-3.0
component  : programming.tools
summary    : Offline documentation browser inspired by Dash
description: |
    Offline documentation browser inspired by Dash
builddeps  :
    - pkgconfig(glesv2)
    - pkgconfig(libarchive)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(sqlite3)
    - pkgconfig(x11-xcb)
    - pkgconfig(xcb-keysyms)
setup      : |
    %qmake CONFIG+=no_libappindicator
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
