name       : zeal
version    : 0.5.0
release    : 7
source     :
    - https://github.com/zealdocs/zeal/archive/v0.5.0.tar.gz : 3efb7b1b5d9a05f0fc60a6686571f7a4b58fa6f6d66f1baf608e83b10fb1290c
license    : GPL-3.0
component  : programming.tools
summary    : Offline documentation browser inspired by Dash
description: |
    Offline documentation browser inspired by Dash
builddeps  :
    - pkgconfig(glesv2)
    - pkgconfig(libarchive)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(sqlite3)
    - pkgconfig(x11-xcb)
    - pkgconfig(xcb-keysyms)
    - extra-cmake-modules
setup      : |
    mkdir build && cd build
    %cmake ..
build      : |
    %make -C build
install    : |
    %make_install -C build
