name       : zeal
version    : 0.6.1
release    : 11
source     :
    - https://github.com/zealdocs/zeal/archive/v0.6.1.tar.gz : 095c08f9903071849d5c79878abd48237ce1615f16d324afff1873ab6b5f0026
license    : GPL-3.0-or-later
component  : programming.tools
summary    : Offline documentation browser inspired by Dash
description: |
    Zeal is a simple offline documentation browser inspired by Dash.
builddeps  :
    - pkgconfig(libarchive)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(sqlite3)
    - pkgconfig(xcb-keysyms)
    - extra-cmake-modules
setup      : |
    %patch -p1 < $pkgfiles/0001-dont-check-for-updates.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
