name       : zeal
version    : 0.6.0
release    : 8
source     :
    - https://github.com/zealdocs/zeal/archive/v0.6.0.tar.gz : ef307d3ad4f03c76fa5fc249f8e7e04de879aa7574bec1ff8be548dbc2c02973
license    : GPL-3.0
component  : programming.tools
summary    : Offline documentation browser inspired by Dash
description: |
    Offline documentation browser inspired by Dash
builddeps  :
    - pkgconfig(glesv2)
    - pkgconfig(libarchive)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(sqlite3)
    - pkgconfig(x11-xcb)
    - pkgconfig(xcb-keysyms)
    - extra-cmake-modules
setup      : |
    mkdir build && cd build
    %cmake ..
build      : |
    %make -C build
install    : |
    %make_install -C build
